// Line-by-line explanations. Each row is [text the code line starts with, explanation (HTML)].
// A row covers that line plus every following line up to the next row's start.
// The code itself is read from the real project files, so it can never drift from the app.
export const explanations = {
  "schema.sql": [
    ["-- Run", "A comment. In SQL, comments start with <code>--</code>. The database ignores it."],
    ["CREATE TABLE", "Make a new table called <code>todos</code>. <code>IF NOT EXISTS</code> means: if it's already there, do nothing instead of crashing."],
    ["id", "Column 1: <code>id</code>. <code>SERIAL</code> = Postgres fills in 1, 2, 3... for you. <code>PRIMARY KEY</code> = no two rows can share an id. (Like Mongo's <code>_id</code>, but a simple number.)"],
    ["text", "Column 2: <code>text</code>, the task name. <code>TEXT</code> = any length string. <code>NOT NULL</code> = it must always have a value."],
    ["done", "Column 3: <code>done</code>, true or false. If you don't give one, it starts as <code>FALSE</code>."],
    [");", "Close the column list. The <code>;</code> ends the SQL command."],
  ],

  "tsconfig.json": [
    ["{", "This file is one JSON object of TypeScript settings. <b>create-next-app wrote it for you; you never need to change it.</b>"],
    ['"compilerOptions"', "Everything inside this block tells the TypeScript checker how to behave."],
    ['"target"', "Which JavaScript version to aim for. Next.js handles old browsers itself, so this rarely matters."],
    ['"lib"', "Which built-in type definitions to load: browser things (<code>document</code>, <code>fetch</code>) and modern JavaScript."],
    ['"allowJs"', "Plain <code>.js</code> files are allowed in the project too."],
    ['"skipLibCheck"', "Don't type-check the insides of downloaded libraries. Faster, and avoids errors that aren't yours."],
    ['"strict"', "Turn on all the strict safety checks. This is the whole point of TypeScript: catching mistakes like using something that might be <code>undefined</code>."],
    ['"noEmit"', "TypeScript only <b>checks</b>; it doesn't produce any files. Next.js does the real compiling."],
    ['"esModuleInterop"', "Lets <code>import</code> work smoothly with older libraries (like <code>pg</code>)."],
    ['"module"', "Use modern <code>import</code> / <code>export</code> syntax."],
    ['"moduleResolution"', "Find imported files the way modern bundlers (like Next.js) do."],
    ['"resolveJsonModule"', "You may <code>import</code> a <code>.json</code> file."],
    ['"isolatedModules"', "Every file must make sense on its own. Next.js's fast compiler needs this."],
    ['"jsx"', "How to treat the HTML-looking <code>&lt;div&gt;</code> code in <code>.tsx</code> files. You don't need to import React in every file."],
    ['"incremental"', "Remember the last check so the next one is faster. That's what the <code>tsconfig.tsbuildinfo</code> cache file is."],
    ['"plugins"', "Turns on the Next.js helper inside your editor (better autocomplete and warnings)."],
    ['"paths"', "A shortcut: <code>@/</code> means \"the project's root folder\". So <code>import { pool } from \"@/lib/db\"</code> works from any folder, with no <code>../../..</code>. The <code>}</code> after it closes <code>compilerOptions</code>."],
    ['"include"', "Which files to check: every <code>.ts</code>/<code>.tsx</code> file, plus types that Next.js generates inside <code>.next/</code>."],
    ['"exclude"', "Never check <code>node_modules</code> (the downloaded libraries)."],
  ],

  "next.config.ts": [
    ["import type", "Bring in the <i>type</i> <code>NextConfig</code>, so your editor can autocomplete valid settings. (<code>import type</code> = only used for checking, removed when the app runs.)"],
    ["const nextConfig", "The settings object. It's empty, which means \"use all the defaults\". This is where you'd later add things like image domains or redirects."],
    ["export default", "Hand the settings to Next.js. It reads this file when <code>npm run dev</code> starts."],
  ],

  ".env.example": [
    ["DATABASE_URL", "One setting, written as an address: <code>postgres://USER:PASSWORD@HOST:PORT/DATABASE</code>. Read it as: log in as user <code>postgres</code> with your password, on this computer (<code>localhost</code>), port <code>5432</code>, database <code>todo_app</code>. Code reads it with <code>process.env.DATABASE_URL</code>."],
  ],

  "lib/db.ts": [
    ["import { Pool }", "Bring in <code>Pool</code> from the <code>pg</code> library (the Node.js driver for PostgreSQL)."],
    ["// A Pool", "Comments. Read the pool deep-dive below for the full story."],
    ["function createPool", "A small function that builds a new pool. The only setting is the database address from <code>.env.local</code>. Everything else uses <code>pg</code>'s defaults (up to 10 connections)."],
    ["// In development", "Comments explaining the next three lines: a fix for a development-only problem."],
    ["const globalForDb", "<code>globalThis</code> is an object that survives when Next.js reloads your files. This line tells TypeScript: \"treat it as an object that <i>might</i> have a <code>pool</code> on it\". (<code>as unknown as ...</code> is a TypeScript cast, i.e. \"trust me on the type\".)"],
    ["export const pool", "The pool everyone uses. <code>??</code> means \"if the left side is empty, use the right side\". So: reuse the saved pool if one exists, otherwise create a new one."],
    ["if (process.env", "While developing (not in production), save the pool on <code>globalThis</code>, so after the next reload the line above finds it and reuses it."],
  ],

  "models/todo.ts": [
    ["import { pool }", "Bring in the shared pool from <code>lib/db.ts</code>. <code>@/</code> means the project root."],
    ['// The "model"', "Comments: this file is the only place that writes SQL. Every other file just calls these functions."],
    ["// Shape", "A TypeScript <b>type</b> describing one row of the table. It matches <code>schema.sql</code> column by column. Other files import it so TypeScript knows what a todo looks like."],
    ["// SELECT", "<code>findAllTodos()</code>: returns every todo. <code>async</code> = it takes time (talking to the database). <code>Promise&lt;Todo[]&gt;</code> = \"later, you'll get an array of Todos\"."],
    ['const { rows } = await pool.query<Todo>("SELECT', "Send SQL to Postgres and <code>await</code> (wait for) the answer. <code>&lt;Todo&gt;</code> tells TypeScript what each row looks like. The result object has a <code>rows</code> array; <code>{ rows }</code> pulls it out. <code>ORDER BY id</code> = oldest first."],
    ["return rows;", "Give the array back to whoever called this function."],
    ["// INSERT", "<code>createTodo(text)</code>: adds one row and returns it."],
    ["const { rows } = await pool.query<Todo>(", "<code>$1</code> is a <b>placeholder</b>; the real value comes from the array <code>[text]</code>. Postgres keeps value and SQL separate, so a user typing SQL can't break your query (this is called preventing <b>SQL injection</b>). <code>RETURNING *</code> = send back the row you just made, including its new <code>id</code>."],
    ["return rows[0];", "There's exactly one new row, so return the first item."],
    ["// UPDATE", "<code>updateTodoDone(id, done)</code>: changes the done flag of one row."],
    ["const { rows }", "<code>$1</code> gets <code>done</code>, <code>$2</code> gets <code>id</code> (same order as the array). <code>WHERE id = $2</code> = only touch that one row."],
    ["return rows[0];", "Return the updated row. If no row had that id, <code>rows</code> is empty, so this returns <code>undefined</code> (the API turns that into a 404)."],
    ["// DELETE", "<code>deleteTodo(id)</code>: removes one row. <code>Promise&lt;void&gt;</code> = it returns nothing."],
    ["await pool.query", "Run the DELETE and wait for it to finish."],
  ],

  "app/api/todos/route.ts": [
    ["import { NextResponse }", "<code>NextResponse</code> is how you build the reply: JSON data plus a status code."],
    ["import { createTodo", "Bring in the two model functions this file needs."],
    ["// GET", "Because this function is <b>named</b> <code>GET</code>, Next.js runs it for <code>GET /api/todos</code>. The URL comes from the folder path <code>app/api/todos/</code>."],
    ["const todos", "Ask the model for all todos (it runs the SELECT)."],
    ["return NextResponse.json(todos);", "Send them to the browser as JSON. Status is 200 (OK) by default."],
    ["// POST", "Runs for <code>POST /api/todos</code>. <code>req</code> is the incoming request."],
    ["const { text }", "Read the JSON the browser sent, e.g. <code>{ \"text\": \"Buy milk\" }</code>, and take out <code>text</code>."],
    ["if (typeof text", "<b>Validate</b> before touching the database: if <code>text</code> isn't a string, or is only spaces, reply <b>400 Bad Request</b> and stop."],
    ["const todo = await createTodo", "Ask the model to INSERT it (with spaces trimmed off the ends)."],
    ["return NextResponse.json(todo, { status: 201 })", "Reply with the new todo and status <b>201 Created</b>."],
  ],

  "app/api/todos/[id]/route.ts": [
    ["import { NextResponse }", "Same reply helper."],
    ["import { deleteTodo", "The two model functions this file needs."],
    ["type Ctx", "Describes the 2nd thing Next.js passes in: <code>params</code>, which holds the <code>[id]</code> part of the URL. For <code>/api/todos/7</code>, <code>id</code> is <code>\"7\"</code> (always a string). It's a Promise, so you <code>await</code> it."],
    ["// PATCH", "Runs for <code>PATCH /api/todos/7</code>. PATCH = \"change part of something\"."],
    ["const { id }", "Wait for <code>params</code> and take out <code>id</code>."],
    ["const { done }", "Read <code>done</code> from the JSON body, e.g. <code>{ \"done\": true }</code>."],
    ["if (typeof done", "Validate: must be exactly <code>true</code> or <code>false</code>, otherwise <b>400</b>."],
    ["const todo = await updateTodoDone", "Ask the model to UPDATE. <code>Number(id)</code> turns the text <code>\"7\"</code> into the number <code>7</code>."],
    ["if (!todo)", "No row had that id: reply <b>404 Not Found</b>."],
    ["return NextResponse.json(todo);", "Success: send back the updated todo."],
    ["// DELETE", "Runs for <code>DELETE /api/todos/7</code>. <code>_req</code> starts with <code>_</code> to show we don't use it (we still need it, because <code>params</code> is always the 2nd argument)."],
    ["const { id }", "Get the id from the URL."],
    ["await deleteTodo", "Ask the model to DELETE that row."],
    ["return new NextResponse", "Reply <b>204 No Content</b>: \"done, nothing to send back\"."],
  ],

  "store/todoStore.ts": [
    ["import { create }", "<code>create</code> is Zustand's one main function. It builds a store."],
    ["import type { Todo }", "Reuse the <code>Todo</code> type from the model. <code>import type</code> brings in only the type, never the database code, so it's safe in the browser."],
    ["// What the store holds", "The TypeScript type of the store: one piece of data (<code>todos</code>) and four <b>actions</b> (functions). <code>() =&gt; Promise&lt;void&gt;</code> = \"a function that does async work and returns nothing\"."],
    ["// create() makes a hook", "Comments on the next line."],
    ["export const useTodoStore", "Build the store. You get two helpers: <code>set</code> (change the data, which re-draws any component using it) and <code>get</code> (read the current data). The result, <code>useTodoStore</code>, is a <b>hook</b> that components call."],
    ["todos: []", "Starting data: an empty list."],
    ["loadTodos: async", "Action: GET the list from the API, then <code>set({ todos: ... })</code>. Every component showing <code>todos</code> re-draws automatically."],
    ["addTodo: async", "Action: add a todo."],
    ['await fetch("/api/todos", {', "Send a <b>POST</b> request. <code>headers</code> says \"the body is JSON\"; <code>JSON.stringify</code> turns <code>{ text }</code> into a JSON string."],
    ["await get().loadTodos();", "Then reload the list from the database, so the screen shows exactly what's saved."],
    ["toggleTodo: async", "Action: flip done/not done for one todo."],
    ["await fetch(`/api/todos/${todo.id}`", "Send a <b>PATCH</b> to <code>/api/todos/&lt;id&gt;</code>. The backticks <code>`...${}`</code> insert the id into the URL. <code>!todo.done</code> = the opposite of its current value."],
    ["await get().loadTodos();", "Reload the list."],
    ["removeTodo: async", "Action: delete one todo."],
    ["await fetch(`/api/todos/${id}`", "Send a <b>DELETE</b> to <code>/api/todos/&lt;id&gt;</code>."],
    ["await get().loadTodos();", "Reload the list. The <code>}));</code> closes the store object, the arrow function and <code>create(</code>."],
  ],

  "app/layout.tsx": [
    ["// layout.tsx", "Comment: the layout is the frame around every page."],
    ["export const metadata", "Page info for the browser. <code>title</code> is the text on the browser tab."],
    ["export default function", "The layout component. Next.js gives it <code>children</code> (the page being shown). The type says <code>children</code> is anything React can display."],
    ["return (", "What this component draws."],
    ["<html", "The outer HTML tag. Next.js requires the root layout to include <code>&lt;html&gt;</code> and <code>&lt;body&gt;</code>. <code>lang=\"en\"</code> = English page."],
    ["<body", "The page body. The <code>style</code> uses a simple font, max width 400px, and <code>margin: \"40px auto\"</code> centers it."],
    ["{children}", "The current page (<code>page.tsx</code>) is placed here."],
    ["</body>", "Closing tags."],
    [");", "End of what's drawn, end of the function."],
  ],

  "app/page.tsx": [
    ['"use client"', "This component runs in the <b>browser</b>. Needed because it uses hooks and click handlers. (Without it, Next.js runs components on the server.)"],
    ["import { useEffect", "Two built-in React hooks: <code>useState</code> (remember a value) and <code>useEffect</code> (run code after the page shows)."],
    ["import { useTodoStore }", "Our Zustand store hook."],
    ["export default function Home", "The page. Next.js shows it at <code>/</code> because it's <code>app/page.tsx</code>."],
    ["// Shared state", "Grab the todo list and the four actions from the store. When the store's <code>todos</code> change, this page re-draws."],
    ["// Local state", "<code>text</code> = what's typed in the box. Only this page needs it, so plain <code>useState</code> is enough. <b>Rule of thumb:</b> used by one component = <code>useState</code>; shared data = store."],
    ["// Load todos", "After the page first appears, call <code>loadTodos()</code>. The <code>[loadTodos]</code> list means \"run again only if this changes\", and it never does, so it runs once."],
    ["async function handleAdd", "Runs when you click Add or press Enter."],
    ["if (!text.trim())", "Ignore empty input."],
    ["await addTodo(text)", "Call the store action (which POSTs to the API and reloads the list)."],
    ['setText("")', "Clear the input box."],
    ["return (", "Below is JSX: HTML-like code that describes the screen."],
    ["<main>", "A container and a heading."],
    ["<input", "The text box. <code>value={text}</code> shows the state. <code>onChange</code> saves each keystroke into the state. <code>onKeyDown</code>: Enter calls <code>handleAdd()</code>. <code>placeholder</code> = grey hint text."],
    ["<button onClick={handleAdd}", "The Add button."],
    ["<ul>", "A bullet list."],
    ["{todos.map", "<code>{ }</code> = \"JavaScript here\". <code>.map</code> turns each todo into one <code>&lt;li&gt;</code>."],
    ["<li", "One item. <code>key</code> = a unique id so React can track items. Use the database id."],
    ['<input type="checkbox"', "Shows <code>done</code>. Clicking calls the store's <code>toggleTodo</code>."],
    ["<span", "The task text, crossed out if done."],
    ["<button onClick={() => removeTodo", "Delete button. <code>() =&gt; ...</code> wraps the call so it runs on click, not immediately."],
    ["</li>", "End of one item; end of <code>.map</code>."],
    ["</ul>", "Close the list and container; end of the component."],
  ],
};
